name: logit_graph
channels:
  - pip
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.16
  - pip
  - pandas
  - numpy
  - scipy
  - tqdm
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - statsmodels
  - lightgbm
  - seaborn
  - fastparquet
  - pip:
    - ICPy
    - lingam
